### ISSUE TITLE
Cannot install into a directory with spaces

### ISSUE THREAD

**Issue by egelja** [unInstance/untldr#3]
`mkdir` needs to quote everything: `"$(DESTDIR)$(PREFIX)/bin"`

https://github.com/unInstance/untldr/blob/d8d35bb00228152fc6d4c3179b94db2bee1facd3/Makefile#L40

**Comment by kovmir** [comment]
Thank you for the involvement! I have enabled e-mail notifications from GitHub, so further reviews of contributions will, hopefully, not take that long.
