### ISSUE TITLE
Custom pages?

### ISSUE THREAD

**Issue by neezer** [unInstance/untldr#6]
This is pretty great (works great on OpenBSD too), but I'd love to add custom pages for my local scripts & commands.

What about being able to specify a second lookup directory path? tinytldr could look there first, then fallback to the one specified in `PAGES_PATH`... ?

**Comment by kovmir** [comment]
Great idea. Feel free to submit a pull request, or wait for me to implement it in the nearest future.

**Comment by kovmir** [comment]
That is already possible, just include your folder and re-build page index:

```bash
TLDR_PAGES="$HOME/.local/share/tinytldr/pages"
mkdir "$TLDR_PAGES/mypages"
echo '# My custom page' > "$TLDR_PAGES/mypages/testpage.md"
tldr -u
tldr testpage
```
